---
title: "Tablero flexdashboard-shiny"
output: flexdashboard::flex_dashboard
runtime : shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(datasets)
library(shiny)
library(lubridate)
data("faithful")
```


Column {.sidebar}
-------------------------------
<!-- elementos a controlar--> 
Esta es la información que se presenta en el tablero lateral.

```{r}
# boton de seleccion 1
selectInput("n_breaks","número de cortes :", 
            choices = c(10,20,30,40,50), selected = 20)

# regleta que se corre de majera manual
sliderInput("ancho_banda", "Ajuste de ancho :",
                        min = 0.2, max = 2, value = 1, step = 0.2 )

# seleccion rango entre  dos fechas
dateRangeInput("date_range", "selecione fechas:",
               start =  today()-7,
               end = today(),
               min = today()-60,
               max = today()+60)

```


Column
--------------------------------
### Errupciones del Geyser


```{r}
renderPlot({
      hist(faithful$eruptions, 
           probility =TRUE, 
           breaks = as.numeric(input$n_breaks),
           xlab = "Duración (en minutos)",
          title  =  "Erupciones del Geyser",
          )
  
  dens <- density(faithful$eruptions,
                  adjust = input$ancho_banda)
  lines(dens, col = "red")
           })

# renderPlot()
# renderPrint()
# renderTable()
# renderText()

```

